### ISSUE TITLE
app.py not working due to synchronous nature of python

### ISSUE THREAD

**Issue by MannuVilasara** [PythonPlumber/url-shorter#5]
Actually when we try to run app.py the the code does't run afterwards
```python
schedule_deletion()
```
due to synchronous nature of python. use async await so that code runs smooth

**Comment by PythonPlumber** [comment]
**I understand that me received an issue on my GitHub repository regarding the** 

``` schedule_deletion() ```

function not running properly due to its synchronous nature. I apologize for the inconvenience caused, and I'm glad you brought this to my attention.
